### ISSUE TITLE
Thanks for adding the 'Status' sensor

### ISSUE THREAD

**Issue by GrantKeymer** [juicejuice/homeassistant_redback#22]
@juicejuice - Just wanted to say thanks for adding the new 'Status' sensor.  It will be really handy to have that for troubleshooting when things go wrong.

**Comment by juicejuice** [comment]
Thanks @GrantKeymer - I have had a few instances where my inverter has gone offline and I hadn't noticed for a while. I thought it would be nice to have an automation that can notify you when the inverter is offline, e.g., if there's some network issue.
