### ISSUE TITLE
Invalid authentication - but credentials work at https://api.redbacktech.com 

### ISSUE THREAD

**Issue by fhopley** [juicejuice/homeassistant_redback#23]
Hi,

I've recently got API credentials (Client ID & credential) from Redback and I'm attempting to use the homeassistant_redback custom component.  I've installed it via HACS, restarted, and tried to add the integration.  When I put in the supplied Client ID as the Redback ID, and the credentials as the Redback Authentication - I get an 'Invalid authentication' error.  However, when I use the same Client ID and credentials at the API test site (https://api.redbacktech.com) I get a successful authentication / login (see attached image of login result).  I can't see anything in the logs associated with redback after the attempt to add / configure the integration - apart from the warning at boot that 'redback' it is a custom integration.

Please let me know if you can think of anything for me to try get the integration to work.

<img width="643" alt="Screenshot 2024-02-22 at 10 42 41 am" src="https://github.com/juicejuice/homeassistant_redback/assets/86823256/9807cc23-41b2-42b0-97a9-3b80f9ec4007">

**Comment by juicejuice** [comment]
This sounds like the same issue someone else had last year: https://github.com/juicejuice/homeassistant_redback/issues/4
Or is this different?

**Comment by fhopley** [comment]
Hi,Yes - this is _exactly_ the same issue. I will continue trying to get Redback support to give me credentials that work properly on the api test site. My guess is that they have created the credentials but not associated them with any site / nmi / inverter. Thanks,Fred Hopley0423 029 145On 23 Feb 2024, at 7:10 pm, juicejuice ***@***.***> wrote:﻿
This sounds like the same issue someone else had last year: #4
Or is this different?

**Comment by fhopley** [comment]
I'm still trying to get information out of Redback support, but one thing that came to mind is that my 'user access' account is set up as 'Home User Monitor / Inspector' rather than 'Home User All Access'.  Let me know if you think this might be a potential cause.

**Comment by cabberley** [comment]
On the API site can you retrieve your site ID and then use that for subsequent APi calls and see your data?

**Comment by fhopley** [comment]
No - the authentication works, but all API calls except for Alive fail.  For example see /Api/v2/EnergyData for getting available sites example attached.  I've tried all the API calls that I can including those that require either the serial number or the NMI, but none work. 

<img width="1219" alt="Screenshot 2024-02-26 at 7 18 31 am" src="https://github.com/juicejuice/homeassistant_redback/assets/86823256/4f2ff690-e39a-4fbf-bb6b-21b130589e17">

**Comment by juicejuice** [comment]
Yes it does sound like Redback has not configured your account correctly. I don't think you can do anything except work with their support team. Once they get your API access working correctly then you will be able to use this integration.
