### ISSUE TITLE
Redback Entered Administration

### ISSUE THREAD

**Issue by LachyGoshi** [juicejuice/homeassistant_redback#24]
https://reneweconomy.com.au/australian-home-battery-outfit-redback-enters-voluntary-administration/

Not an issue.... Yet, hopefully our API can stay up, or better still they open up local control.

Not sure what issues it has with warranty etc, but I'll just push my installer for anything.

Sorry for posting here, but this is the best place I know for sharing.

**Comment by BigByte76** [comment]
Also being discussed over on whirlpool below. Hopefully they end up opening full local access.

https://forums.whirlpool.net.au/thread/324651l8

**Comment by juicejuice** [comment]
I did contact our installer already and he says that it is quite likely Redback may be acquired. They have a reasonable footprint, strong products, good team, just needs some additional funding to take things forwards. I mentioned that the one thing we would really like is local access (e.g., SSH to the Ouija board) but no news on that yet. If the Redback portal is shutdown then the inverters will be degraded to minimal functionality (no energy monitoring, no scheduling, etc.).

**Comment by LachyGoshi** [comment]
I have just emailed their useless support team and one of the operations managers who handled an earlier complaint to request full local access.... Haha, I don't like my chances but really concerned of loosing web/API. Will let you know of I hear anything.

Thanks for the whirlpool link, I'll jump on that to keep up to date.

**Comment by juicejuice** [comment]
Looks like they found a new owner now: https://redbacktech.com/redback-secures-new-owner/
I'll close this issue as resolved :D
