### ISSUE TITLE
Feature Request: return Inverter Status

### ISSUE THREAD

**Issue by sethkor** [juicejuice/homeassistant_redback#29]
It would be good to get Inverter Status returned into this integration so I can see when my inverter goes offline.  It does this once every couple of months and I only finf out when I check my redback app so would be good to get it in this integration so I can send myself a notification.

Thanks.

**Comment by juicejuice** [comment]
If you're on the latest version of the integration then it does indeed report the Status. I did that for exactly the same reason and use an automation to detect and report if it's been offline for more than a minute :)

**Comment by sethkor** [comment]
Updated and can see it.   Thanks, lets close this.
