### ISSUE TITLE
Charge HQ Integration

### ISSUE THREAD

**Issue by djgoding** [juicejuice/homeassistant_redback#3]
Hi there,
I see that ChargeHQ list your code as a push API integration
https://chargehq.net/kb/push-api
Do you have some further instructions on how this is setup using HomeAssistant to publish the data to them?

**Comment by juicejuice** [comment]
Oh I didn't realise I was linked from ChargeHQ, thanks! I briefly discussed with Andrew from ChargeHQ and he was going to talk with Redback about a proper integration. I'm not sure how much progress he made.
It looks like the ChargeHQ push API lets you feed inverter data into their system - cool! I ended up implementing my own equivalent of ChargeHQ in Home Assistant. It wasn't that hard, I can post up a Youtube video if you like?
Otherwise it looks like you would have to implement some HA scripting to send the Redback entity data over to ChargeHQ. I haven't tried that so don't have any sample code or instructions, sorry.

**Comment by djgoding** [comment]
Yep I'm keen to see what you have implemented

**Comment by djgoding** [comment]
Hi there juicejuice,
I have been doing some further testing with an aim to export the redback solar information to Charge HQ and I was wondering if I am heading down the correct path, please note I am not a programmer, most of this is trial and error.
My thoughts are that I need to create a sensor that pushes the redback inverter values in a JSON payload to ChargeHQ. I guess I will then need to run a script to activate the POST every minute or so?
I have added the following to my configuration.yaml and restarted, however the SENSOR does not get created after I restart and I get the following recurring error in the log, Setup of sensor platform rest is taking over 10 seconds.

sensor:
  - platform: rest
    name: My Redback JSON Data
    resource: https://api.chargehq.net/api/public/push-solar-data
    method: POST
    headers:
      Content-Type: application/json
    payload: >
      {
        "apiKey": "abc12345678901234567890",
        "siteMeters": {
          "consumption_kw": {{ states('sensor.redback_sh4600_inverter_load_total') | float }},
          "net_import_kw": {{ states('sensor.redback_sh4600_inverter_grid_import') | float }},
          "production_kw": {{ states('sensor.redback_sh4600_inverter_solar_generation') | float }},
          "exported_kwh": {{ states('sensor.redback_sh4600_inverter_grid_export_total') | float }},
          "imported_kwh": {{ states('sensor.redback_sh4600_inverter_grid_import_total') | float }}
        }
      }
    json_attributes:
      - siteMeters

**Comment by djgoding** [comment]
This is how the script is actually formatted
![image](https://user-images.githubusercontent.com/128471775/232673108-cdf98c21-2f9c-4480-bad9-59a60f91d67d.png)

**Comment by djgoding** [comment]
Here are the Redback entity IDs that I am referencing in the payload states
![image](https://user-images.githubusercontent.com/128471775/232673622-bf2da0cf-033f-4a64-a60d-1a27cf106144.png)

**Comment by juicejuice** [comment]
Hi @djgoding, sorry but I'm going to close this issue as I've written my own solution for this in HA. I did find this thread though in case it helps? https://community.home-assistant.io/t/pvouput-uploader/46761
