### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by samuelyeats** [juicejuice/homeassistant_redback#30]
Hey @juicejuice - thanks for looking into this - I've got new API credentials that work fine when tested against the Redback API. 

I'm trying to add my Redback entity on your latest version from last week, but I get (1) an "Unexpected error" when clicking save on the Add entity, and  (2) a 500 error on the Home Screen:
Failed setup, will retry: HTTP error: 500 Internal Server Error. {"Error":"Unknown error, please report to Redback Technologies"}

2024-10-18 20:12:33.756 DEBUG (MainThread) [custom_components.redback] Syncing data with Redback (entry_id=01JAFEA8X7X1RFHSE6ZH7PRPSJ)
2024-10-18 20:12:34.220 DEBUG (MainThread) [custom_components.redback] Finished fetching redback data in 0.463 seconds (success: False)
2024-10-18 20:12:44.411 DEBUG (MainThread) [custom_components.redback] Syncing data with Redback (entry_id=01JAFEA8X7X1RFHSE6ZH7PRPSJ)
2024-10-18 20:12:46.724 DEBUG (MainThread) [custom_components.redback] Finished fetching redback data in 2.313 seconds (success: False)

**Comment by juicejuice** [comment]
OK I have something you can try, if you are familiar with command line interface. This should work on Windows 10/11 command prompt or Mac/Linux terminal.

**Step 1. Get auth token from Redback. Use Redback API credentials at XXX and YYY below.**
`curl -X POST -d "client_id=XXX&client_secret=YYY" https://api.redbacktech.com/api/v2/Auth/token`

**Step 2. Step 1 returns an auth token in JSON format, valid for one hour. You need to fish out the really long TOKENSTRING part without its surrounding quotes.**
`{"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"TOKENSTRING"}`

**Step 3. See if you can access one of the Redback API endpoints, replacing TOKENSTRING with that super long auth token from Step 2.**
`curl -H "authorization: Bearer TOKENSTRING" https://api.redbacktech.com/Api/v2/EnergyData`

If one of the steps doesn't work, you can put a ` -v ` flag before the https://api.redbacktech.com bit to get it to spit out more details. Let us know how you go?

**Comment by samuelyeats** [comment]
Hi @juicejuice That seemed to work fine

* Request completely sent off
< HTTP/1.1 200 OK
< Content-Length: 74
< Content-Type: application/json; charset=utf-8
< Date: Tue, 22 Oct 2024 03:17:40 GMT
< Server: Microsoft-IIS/10.0
< Set-Cookie: ARRAffinity=0e5f53c06fe9c8a84e3589fcb7d78a91d5a2ad5b867ea6746e75561303361b04;Path=/;HttpOnly;Secure;Domain=api.redbacktech.com
< Set-Cookie: ARRAffinitySameSite=0e5f53c06fe9c8a84e3589fcb7d78a91d5a2ad5b867ea6746e75561303361b04;Path=/;HttpOnly;SameSite=None;Secure;Domain=api.redbacktech.com
< Request-Context: appId=cid-v1:52b49cfe-5743-4813-b663-63a74f164ccb
< X-Rate-Limit-Limit: 7d
< X-Rate-Limit-Remaining: 19999990
< X-Rate-Limit-Reset: 2024-10-29T03:12:49.3644845Z
< X-Powered-By: ASP.NET
< 
* Connection #0 to host api.redbacktech.com left intact
{"Page":0,"PageSize":100,"PageCount":1,"TotalCount":1,"Data":["S2021893"]}

**Comment by juicejuice** [comment]
That's good, thanks! Those are essentially the commands that the Redback integration is using under the covers. However, that still leaves the question of why yours isn't working within Home Assistant. Any chance you can share some screenshots as you step through the setup process so I can see exactly where and how it is going wrong?

**Comment by samuelyeats** [comment]
Of course, everything up to date except for todays HA Core

![redback4](https://github.com/user-attachments/assets/f817d8e4-8b62-445e-b6c5-995b31190f2e)
![redback1](https://github.com/user-attachments/assets/f88fa215-a420-44a4-9d72-b12d265f13ab)
![redback2](https://github.com/user-attachments/assets/11332944-592f-4b6a-9f39-4d2049f7a344)
![redback3](https://github.com/user-attachments/assets/74e32014-c9a5-4494-8768-6310ade21130)

**Comment by juicejuice** [comment]
Thanks - that doesn't look right. I just did a fresh install of the Redback integration here and it looks somewhat different. Is it possible for you to setup from scratch again and record screenshots like mine to compare against? If you can enable debug logging then that might help give some clues as well.

**Step 1 - add integration**
<img width="545" alt="step1" src="https://github.com/user-attachments/assets/6b9332c1-3d6b-4e77-b7c7-40ceed23deaa">

**Step 2 - enter details**
<img width="545" alt="step2" src="https://github.com/user-attachments/assets/04eb08b3-3cd4-4080-8e02-d216b1a33e45">

**Step 3 - success**
<img width="545" alt="step3" src="https://github.com/user-attachments/assets/d61aa2bc-dd30-49b7-a181-6ab1986a548d">

**Step 4 - check device page**
<img width="545" alt="step4" src="https://github.com/user-attachments/assets/8fbe6696-1752-4214-b4ad-828b63c11b91">

**Step 5 - check entities**
<img width="607" alt="step5" src="https://github.com/user-attachments/assets/eb15cecb-ad07-4e5b-a137-1c8c51fdceaf">

**Comment by samuelyeats** [comment]
Thanks for looking into this. This has subsequently been resolved by redback following a firmware upgrade of my system. As a FYI if anyone else experiences this issue, call redback select #3 for upgrade support.

**Comment by samuelyeats** [comment]
Thanks for looking into this. This has subsequently been resolved by redback following a firmware upgrade of my system. As a FYI if anyone else experiences this issue, call redback select #3 for upgrade support.

**Comment by juicejuice** [comment]
Awesome! Thanks @samuelyeats for reporting back on this.

**Comment by GrantKeymer** [comment]
Earlier this week I needed to reconfigure the Redback integration and thought nothing more of it.

However, the same thing happened today and now the reconfiguration is unsuccessful.  I'm see this error message displayed:

`Retrying setup: HTTP error: 500 Internal Server Error. {"Error":"Unknown error, please report to Redback Technologies"}`

Is anyone else seeing something similar?
