### ISSUE TITLE
3-Phase Energy Meter with SH5000

### ISSUE THREAD

**Issue by GrantKeymer** [juicejuice/homeassistant_redback#9]
Here is something interesting, which isn't really an issue...

Last night I installed the latest Redback update after noticing a mention of Daily Hassfest Refresh being changed.  I still don't know what that is, but thought it wouldn't hurt to have the update.  Also included was the previous update regarding 3-phase metering, which I didn't expect would change anything given that my SH5000 inverter is single phase.

However, a few minutes ago I noticed that the 'Grid Voltage' was now saying 420V instead of the previous 240V.  Upon looking further I now have individual readings for Grid Voltage A, B and C which weren't there before.  This is very valuable info to have as my neighbour has just installed a Solar Power system with Export enabled at last.

I was concerned that we might be exporting on the same phase of our shared transformer, thus driving the voltage up on the phase I'm using, which could lead to problems as it was already approaching 250V on sunny days.  However, with the extra readings now available, I can see we're exporting on different phases, which is a relief.

A word of further explanation is in order.  When my system was originally installed, it had only the Acrel single-phase energy meter.  My installer replaced this with a 3-phase SM-3000 at my request.  Using the extra 2 CTs turned out to be not a great idea usability wise, but it gave me extra metering data to show my overall energy consumption.  After having the system running with all 3 CTs for a couple of years, I installed a separate 2-phase energy meter last year to give me the extra data I wanted and removed the additional 2 CTs connected to the SM-3000.  It is still connected to all 3 phases for voltage input though, as otherwise my Grid Voltage reads about 80V.

Thanks to JuiceJuice, I now have access to individual voltage readings from each of the 3 phases, which were available all along via the API, but never in the web portal.  Great work 👍 💯 🥇

**Comment by juicejuice** [comment]
Thanks for the kind words @GrantKeymer!
Yes, I made a quick "hassfest" change this week. The hassfest is some automated testing that ensures my code will work nicely with Home Assistant. My change this week was to disable the daily hassfest checks as I am only updating the Redback code on an adhoc basis. Instead, it now runs the hassfest tests only when I make changes.
Regards grid voltage sensors: the grid voltage changes were done in response to a request from another user. That user has single phase supply but was receiving weird voltage readings. He wanted individual per-phase voltage to check his metering and supply. Long story short, the 420V "grid voltage" sensor is now showing the estimated phase-to-phase voltage that is available within the 3-phase supply and the individual phases are now reported. Seems a much better approach 👍
